### ISSUE TITLE
Hide error messages at boot?

### ISSUE THREAD

**Issue by neilmunday** [T4d3o/Plymouth-lite#1]
Hi @T4d3o ,

Thanks for creating this project.

Having followed your instructions I have managed to get a custom splash screen working on my Raspberry Pi 3 using Arch Linux. However, during boot two errors from the brcmf_cfg kernel module (a known firmware issue) are shown over the top of the splash image.

Is there anyway to hide these messages (other than blacklisting the kernel module!)?

Thanks,

Neil.

**Comment by T4d3o** [comment]
Hi.

Now I do not have much time, you've tried this? http://raspberrypi.stackexchange.com/questions/36657/hide-complete-boot-message-from-rpi-booting#36663

Regards.

**Comment by neilmunday** [comment]
Thanks @T4d3o , that did the trick!
